config/routes.rb
Rails.application.routes.draw do
  root 'alchols#index'

  resources :alchols 
  # get 'search' => 'posts#search'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/alchol.rb
class Alchol < ApplicationRecord
  mount_uploader :image, ImageUploader  
  mount_uploader :placephoto, ImageUploader  
  
  validates :name, presence: true
  
  
  scope :search, -> (search_params) do   #検索機能
    return if search_params.blank?
    name_like(search_params[:name])
  end  
  scope :name_like, -> (name) { where('name LIKE ?', "%#{name}%") if name.present? }
  
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/controllers/alchols_controller.rb
class AlcholsController < ApplicationController
  
  def new
   @alchol = Alchol.new
  end
  
  def show
    @alchol = Alchol.find(params[:id])
  end
  
  def index
    # @alchols = Alchol.all
    @search_params = alchol_search_params
    @alchols = Alchol.search(@search_params)
  end
  
  def create
    @alchol = Alchol.new(alchol_params)
    if @alchol.save
      flash[:success] = '新規作成に成功しました。'
      redirect_to alchols_url
    else
      render :new
    end
  end
  
  def edit 
    @alchol = Alchol.find(params[:id])
  end
  
  def update
    @alchol = Alchol.find(params[:id])
    if @alchol.update_attributes(alchol_params)
      flash[:success] = "更新しました。"
      redirect_to alchols_url
    else
      render :edit
      
    end
  end
  
  def destroy
    @alchol = Alchol.find(params[:id])
    @alchol.destroy
    flash[:success] = "#{@alchol.name}を削除しました。"
    redirect_to alchols_url
  end
  
  
  private

    def alchol_params
      params.require(:alchol).permit(:name, :price, :kind, :image, :character, :placephoto)
    end
    
    def alchol_search_params
      params.fetch(:search, {}).permit(:name, :price, :image, :character, :kind, :placephoto)
    end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/static_page_controller.rb
class StaticPageController < ApplicationController
  def top
    
  end
end

app/helpers/alchols_helper.rb
module AlcholsHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
  
  def full_title(page_name = "")
    base_title = "Anchor"
    if page_name.empty?
      base_title
    else
      page_name + " | " + base_title
    end
  end
end

app/helpers/static_helper.rb
module StaticHelper
end

app/helpers/static_page_helper.rb
module StaticPageHelper
end

app/views/alchols/edit.html.erb
<% provide(:title, "Edit") %>
<h1>お酒情報の更新</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @alchol, local: true) do |f| %>
      <%= render 'shared/error_messages' %>
      
      <%= f.label :image, class: "label-new" %>
    　<%= f.file_field :image %>
      
      <%= f.label :name, class: "label-edit" %>
      <%= f.text_field :name, class: "form-control" %>
      
      <%= f.label :price, class: "label-edit" %>
      <%= f.text_field :price, class: "form-control" %>
      
      <%= f.label :kind, class: "label-new" %>
      <%= f.text_field :kind, class: "form-control" %>
      
      <%= f.label :character, class: "label-new" %>
      <%= f.text_field :character, class: "form-control" %>

      
      <%= f.submit  "更新", class: "btn btn-primary btn-block btn-alchol-edit" %>
    <% end %>
  </div>
</div>

app/views/alchols/index.html.erb
<% provide(:title, "All") %>

<div class="center jumbotron">
  <h1>Anchor Eco System</h1>
  <p>このシステムではお酒の種類や場所を検索することができます</p>
</div>


<div class="search">
  <h2>Alcohol Searth</h2>
  <%= form_with(scope: :search, url: alchols_path, method: :get, local: true, class:"search_form") do |f| %>
    <%= f.label(:name, '名前') %>
    <%= f.text_field :name %>
    <%= f.submit('検索') %>
    
  <% end %>
</div>
  
<div class="col-md-10 col-md-offset-1">
  <table class="table table-bordered table-condensed user-table">
    <thead>
      <tr>
        <td>写真</td>
        <td>名前</td>
        <td>価格</td>
        <td>場所</td>
        <td>種類</td>
        <td>特徴</td>
        
        <td></td>
        <td></td>
      </tr>
    </thead>
     <% @alchols.each do |alchol| %>
      <tr>
         <td>
           <%=  link_to alchol.image.url, 'data-lightbox': alchol.image do %>
             <%= image_tag alchol.image.thumb.url if alchol.image? %>
           <% end %>
          
         </td>
          
          <td><%= alchol.name %></td>
          <td><%= alchol.price %></td>
          <td>
           <%=  link_to alchol.placephoto.url, 'data-lightbox': alchol.placephoto do %>
             <%= image_tag alchol.placephoto.thumb.url if alchol.placephoto? %>
           <% end %>
          
         </td>
          <td><%= alchol.kind %></td>
          <td><%= alchol.character %></td>
          <td><%= link_to "編集", edit_alchol_path(alchol), class: "btn btn-primary" %></td>
          <td><%= link_to "削除", alchol, method: :delete,
                data: { confirm: "削除してよろしいですか？" },
                class: "btn btn-danger" %>
          </td>
      </tr>
      <% end %>

    
  </table>
</div>

app/views/alchols/new.html.erb
<% provide(:title, 'new') %>
<h1>お酒登録</h1>

<div class="row">
  <div class="col-md-6 col-md-offset-3">
    <%= form_with(model: @alchol, local: true) do |f| %>
    <%= render 'shared/error_messages' %>
    
    　<%= f.label :image, class: "label-new" %>
    　<%= f.file_field :image %>
    　
      <%= f.label :name, class: "label-new"%>
      <%= f.text_field :name, class: "form-control" %>

      <%= f.label :price, class: "label-new" %>
      <%= f.text_field :price, class: "form-control" %>
      
      <%= f.label :placephoto, class: "label-new" %>
      <%= f.file_field :placephoto %>
      
      <%= f.label :kind, class: "label-new" %>
      <%= f.text_field :kind, class: "form-control" %>
      
      <%= f.label :character, class: "label-new" %>
      <%= f.text_field :character, class: "form-control" %>

      <%= f.submit "新規登録", class: "btn btn-primary btn-block btn-new-alchol" %>
    <% end %>
  </div>
</div>

app/views/alchols/show.html.erb
<% provide(:title, @alchol.name) %>
<h1><%= @alchol.name %></h1>

app/views/layouts/_header.html.erb
<header class="navbar navbar-fixed-top navbar-inverse">
  <div class="container">
    <%= link_to "Anchor", root_path, id: "logo" %>
    <nav>
      <ul class="nav navbar-nav navbar-right">
        <li><%= link_to "Top", root_path %></li>
        <li><%= link_to "登録", new_alchol_path %></li>
      </ul>
    </nav>
  </div>
</header>

app/views/layouts/_shim.html.erb
<!--[if lt IE 9]>
  <script src="//cdnjs.cloudflare.com/ajax/libs/html5shiv/r29/html5.min.js">
  </script>
<![endif]-->

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title><%= full_title(yield(:title)) %></title>
    <%= csrf_meta_tags %>
    <%= stylesheet_link_tag    'application', media: 'all',
                               'data-turbolinks-track': 'reload' %>
    <%= javascript_include_tag 'application',
                               'data-turbolinks-track': 'reload' %>
                               
    <link href="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/css/lightbox.css" rel="stylesheet">
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/lightbox2/2.7.1/js/lightbox.min.js" type="text/javascript"></script>
    <%= render 'layouts/shim' %>
   
   
  </head>
  <body>
    <%= render 'layouts/header' %>
    <div class="container">
      <% flash.each do |message_type, msg| %>
        <div class="alert alert-<%= message_type %>"><%= msg %></div>
      <% end %>
      <%= yield %>
      <%= debug(params) if Rails.env.development? %>
    </div>
  </body>
</html>

app/views/shared/_error_messages.html.erb
<% if @alchol.errors.any? %>
  <div id="error_explanation">
    <div class="alert alert-danger">
      The form contains <%= pluralize(@alchol.errors.count, "error") %>.
    </div>
    <ul>
    <% @alchol.errors.full_messages.each do |msg| %>
      <li><%= msg %></li>
    <% end %>
    </ul>
  </div>
<% end %>

app/views/static_page/top.html.erb
<% provide(:title, "Top") %>
<div class="center jumbotron">
  <h1>Anchor Eco System</h1>
  <p>このシステムではお酒の種類や場所を検索することができます</p>
</div>